global using System.Diagnostics;
global using System.Runtime.InteropServices;
global using System.Text.Json;
global using CliFx;
global using CliFx.Attributes;
global using CliFx.Exceptions;
global using CliFx.Infrastructure;
global using Microsoft.Extensions.DependencyInjection;
global using Serilog;
